import * as fs from 'fs';
import * as path from 'path';
import { OptimisationResult, ScanResult, CarbonEstimate, GreenPipeConfig } from './types';

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
}

function formatMB(bytes: number): string {
  return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
}

function pct(n: number): string {
  return `${n.toFixed(1)}%`;
}

export function generateReport(
  scanResult: ScanResult,
  optimisationResult: OptimisationResult,
  carbon: CarbonEstimate,
  config: GreenPipeConfig,
  repoName: string
): string {
  const now = new Date().toISOString().split('T')[0];
  const { optimised, skipped, failed } = optimisationResult;

  const totalOriginalBytes = scanResult.totalSize;
  const totalOptimisedBytes =
    optimised.reduce((sum, r) => sum + r.optimisedSize, 0) +
    skipped.reduce((sum, r) => sum + r.file.size, 0);
  const totalSavedBytes = optimisationResult.totalSavedBytes;
  const totalSavedPct =
    totalOriginalBytes > 0 ? (totalSavedBytes / totalOriginalBytes) * 100 : 0;

  const avgBefore =
    scanResult.totalCount > 0 ? totalOriginalBytes / scanResult.totalCount : 0;
  const avgAfter =
    optimised.length > 0
      ? optimised.reduce((sum, r) => sum + r.optimisedSize, 0) / optimised.length
      : avgBefore;

  const co2Before = ((totalOriginalBytes / 1e9) * 0.6 * carbon.monthlyViews * 12).toFixed(1);
  const co2After = (
    ((totalOriginalBytes - totalSavedBytes) / 1e9) *
    0.6 *
    carbon.monthlyViews *
    12
  ).toFixed(1);

  const optimisedRows = optimised
    .map((r) => {
      return `| ${r.original.relativePath} | ${formatBytes(r.original.size)} | ${formatBytes(r.optimisedSize)} | ${pct(r.savedPercent)} | ${r.formatConversion} |`;
    })
    .join('\n');

  const skippedRows = skipped
    .map((r) => `| ${r.file.relativePath} | ${formatBytes(r.file.size)} | ${r.reason} |`)
    .join('\n');

  const failedSection =
    failed.length > 0
      ? `\n## Failed\n\n| File | Error |\n|------|-------|\n${failed
          .map((r) => `| ${r.file.relativePath} | ${r.error} |`)
          .join('\n')}\n`
      : '';

  const duplicatesSection =
    scanResult.duplicates.length > 0
      ? `\n## Duplicates\n\n| Hash | Files | Action |\n|------|-------|--------|\n${scanResult.duplicates
          .map(
            (d) =>
              `| \`${d.hash.slice(0, 8)}\` | ${d.files.join(', ')} | Remove duplicate, reference one path |`
          )
          .join('\n')}\n`
      : '';

  return `# Green Pipe — Optimisation Report

**Repository:** ${repoName}
**Date:** ${now}
**Assets scanned:** ${scanResult.totalCount}

---

## Summary

| Metric | Before | After | Saved |
|--------|--------|-------|-------|
| Total size | ${formatMB(totalOriginalBytes)} | ${formatMB(totalOptimisedBytes)} | ${formatMB(totalSavedBytes)} (${pct(totalSavedPct)}) |
| Average asset | ${formatBytes(Math.round(avgBefore))} | ${formatBytes(Math.round(avgAfter))} | ${formatBytes(Math.round(avgBefore - avgAfter))} |
| Annual CO₂e (est.) | ${co2Before}g | ${co2After}g | ${carbon.annualCO2Grams.toFixed(1)}g |

At an estimated ${carbon.monthlyViews.toLocaleString()} monthly views:
- ${carbon.smartphoneCharges.toFixed(1)} smartphone charges saved per year
- ${carbon.drivingKm.toFixed(2)} km of driving avoided per year
- ${formatMB(totalSavedBytes)} less bandwidth per month

---

## Optimised

${
  optimised.length > 0
    ? `| File | Before | After | Saved | Format |\n|------|--------|-------|-------|--------|\n${optimisedRows}`
    : '_None._'
}

## Skipped (below ${config.threshold}% threshold)

${
  skipped.length > 0
    ? `| File | Size | Reason |\n|------|------|--------|\n${skippedRows}`
    : '_None._'
}
${failedSection}${duplicatesSection}
---

## Methodology

Optimised with [Cloudinary](https://cloudinary.com) automatic quality and format selection.

Carbon estimates use 0.6g CO₂e per GB transferred ([The Shift Project](https://theshiftproject.org), IEA).
Monthly views are configurable via \`--monthly-views\`. Figures are estimates and will vary
by CDN, geography, and caching behaviour.

Reference values: 1 smartphone charge = 8.22g CO₂e, 1 km average car = 120g CO₂e.

---

_Generated by [green-pipe](https://github.com/Princesso/green-pipe)_
`;
}

export function saveReport(content: string, outputPath: string): void {
  const dir = path.dirname(path.resolve(outputPath));
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(outputPath, content, 'utf-8');
}
